### PR TITLE
delete change_event_link_name migrate file because event_link column …

### PR DESCRIPTION
**Pull request by kaweir**
delete change_event_link_name migrate file because event_link column didn't exist. Migrate file renamed event_link to url but the url field already existed and event_link did not. So migration caused an error when db:migrate was run. I don't know about: add_index "users", ["slug"], name: "index_users_on_slug"

### CODE REVIEW

**Comment by sweir27** [comment]
Looks good! Can you add a screenshot of what the final website looks like with the new photos? They seem to be much smaller than the previous ones, so I'm curious what they look like.

**Comment by kaweir** [comment]
screen shot 2016-04-19 at 11 43 53 am

**Comment by kaweir** [comment]
screen shot 2016-04-19 at 11 46 27 am

This shows the Third thursday on the Edit/Create show page

**Comment by kaweir** [comment]
Ok added two screenshots

**Comment by sweir27** [comment]
Thanks! Looks good

**Pull request merged**
